modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "jcraft_sf"
version = "${version}"
displayName = "JCraft Stone Free Addon"
authors = "Arsik"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "assets/jcraft_sf/icon.png"

[[dependencies.jcraft_sf]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraft_sf]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jcraft_sf]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jcraft_sf]]
modId = "jcraft"
mandatory = true
versionRange = "[0.18.0,)"
ordering = "AFTER"
side = "BOTH"
